### ISSUE TITLE
webserver /image does not respond

### ISSUE THREAD

**Issue by luotope** [MikaelBertze/HallonDispDevices#2]
I'm trying to test this project, but am having problems with getting the image. The webserver does work as when I'm using a browser with URI /configuration, I'm getting the json -response. But if I try with /image/1 there is no response at all (or browser displays error 500). The same is when I'm running your script to retrieve image and convert it (mentioned in the other issue) unchanged nothing but the ip , using windows/python/VC), the response is the same error 500. 

So, what is wrong? It looks it does not even get into the code starting with "server.on("^\\/image\\/([0-9])$", HTTP_GET,..."

Thanks for any hint.

**Comment by MikaelBertze** [comment]
Sorry for the late reply. I missed this issue post :-(
Did you get it to work?
in #1 I posted some python code that I use for calibrating the device. The url providing the images for calibration should indeed be on the route /image/{x} where x is a int value 1-3

Did you try running the device connected to a serial monitor? The ESP-32-CAM has a tendency to crash if the camera is not connected correctly... Did you get any other camera code working on your esp?

**Comment by luotope** [comment]
Thanks for your response. I got the code working and the solution was similar as in #1:
config.jpeg_quality = 10;  Sorry I didn't understand in the first place it was the same issue actually. Now the code reports status to my broker, but I have not yet connected the camera to my water meter. I'm planning to use printed pictures  of the water meter which camera is seeing, to verify it works correctly. Have you tried this way ?
Thanks.

**Comment by MikaelBertze** [comment]
I have not tried that, but I don,t see any reason it should not work. The color of the gauge should not matter, the image analysis is only using the saturation, so as long as the gauge background is white it should work. Let me know how it works out for you :-) 

About the jpeg_quality I tried it on my device, but it started crashing for me. I should probably look into that again since both of you had issues with this. I just got a new ESP-32-CAM that I will debug this issue on. 

If you create a gauge picture that works for you I would be happy to include it in the repo. 

Cheers!
Mikael
